### ISSUE TITLE
Registration Error -Double Userprofiles Wrong Verifikation Key

### ISSUE THREAD

**Issue by justelex** [Qwlouse/Findeco#343] opened 2015-02-17 18:34 UTC
On Updating Userprofiles there Occour some Errors.
All Users Have got 2 Userprofiles visible in the Admin module
None of the both verification Keys match to the verification Key sent by mail.
None of the both verification Keys in DB works for activating the User in Frontend.

**Comment by Qwlouse** [comment] 2015-02-22 20:02
Could you explain how you got those problems?
I set up my local SMTP server with the current dev branch and registered a user. 

* I can't reproduce the problem with 2 userprofiles.
* The "Verification key" stored in the user-profile is some Django-internal thing and has nothing to do with the key sent by email and is used for activation.
* But the one in the email works just fine, both with the link and by manually copying the key to http://127.0.0.1:8000/activate 
* The correct activation key (the one from the email) can also be seen from the admin interface by clicking "Activations" instead of "Users"

**Comment by justelex** [comment] 2015-03-08 18:31
I got problems with the activation ( Jonny solved this) On my Investigation I found that in the Django Admin there is a second Userprofile.

**Comment by Qwlouse** [comment] 2015-08-11 20:28
As far as I know this hasn't happened anymore. So I'm closing this issue for now. If you experience the error again, please reopen.

**Closed by Qwlouse** 2015-08-11 20:28 UTC
